plugins {
    id 'com.android.application'
}

android {
    namespace 'com.myai.companion'
    compileSdk 34

    defaultConfig {
        applicationId "com.myai.companion"
        minSdk 24
        targetSdk 34
        versionCode 7
        versionName "1.6"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "android"
            keyAlias "androidkey"
            keyPassword "android"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
